### ISSUE TITLE
Incorrect highlighting of escaped strings in MSON

### ISSUE THREAD

**Issue by neonichu** [apiaryio/api-blueprint-sublime-plugin#22]
![screen shot 2015-05-13 at 17 18 41](https://cloud.githubusercontent.com/assets/118992/7614288/1bad8108-f996-11e4-8139-55144555c9c7.png)

As seen in the screenshot, both date strings should be completely rendered in the same color.

The MSON being used:

```
- sys
    - type: Space
    - id: cfexampleapi
    - version: 3 (number)
    - createdBy
        - sys
            - type: Link
            - linkType: User
            - id: 7BslKh9TdKGOK41VmLDjFZ
    - createdAt: `2013-06-23T19:02:00Z`
    - updatedBy
        - sys
            - type: Link
            - linkType: User
            - id: 7BslKh9TdKGOK41VmLDjFZ
    - updatedAt: `2014-07-09T07:18:20Z`
- name: Contentful Example API
```

**Comment by danielgtaylor** [comment]
Looks like the regular expression needs to be fixed. Right now it starts at the example value and reads until the first of several characters (`-` in this case) is encountered.
