### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by diggers** [apiaryio/api-blueprint-sublime-plugin#27]
I've followed all installation steps and installed all plugins successfully. However, autocomplete and highlighting doesn't seem to work. I can still parse the file and open result AST though.

![screen shot 2015-08-25 at 1 42 13 pm](https://cloud.githubusercontent.com/assets/780680/9458257/9e4bbaf4-4b2f-11e5-99f0-11b3b79b1ea7.png)

I'm not a Sublime user. Am I missing any settings or configuration assumed in the installation instructions?

EDIT:
I've got some coloring selecting:
Preferences > Color Scheme > Monokai Extended > Monokai Extended 

![screen shot 2015-08-25 at 1 52 19 pm](https://cloud.githubusercontent.com/assets/780680/9458365/cc843756-4b30-11e5-8070-4fecb9da517a.png)

However, no autocompletion yet...

**Comment by pksunkara** [comment]
@diggers Did you have drafter installed as mentioned [here](https://github.com/apiaryio/api-blueprint-sublime-plugin#drafter) or [here](https://github.com/apiaryio/api-blueprint-sublime-plugin#from-the-source)?

**Comment by zdne** [comment]
@diggers note there is no autocomplete function in the plug-in at the moment.

**Comment by diggers** [comment]
Thanks @pksunkara and @zdne. All clarified. 
I found it very useful regardless.
