### ISSUE TITLE
Feature-Request : Highlighting for fixed-type and nullable type attributes

### ISSUE THREAD

**Issue by CameronLonsdale** [apiaryio/api-blueprint-sublime-plugin#33]
Part of the MSON spec but not yet supported by this plugin.
https://apiblueprint.org/documentation/mson/specification.html#353-type-attribute

**Comment by pksunkara** [comment]
@CameronLonsdale We would very much appreciate it if you could make a PR.

**Comment by kylef** [comment]
Added in https://github.com/apiaryio/api-blueprint-sublime-plugin/commit/cd4b76c3e46fa7e9e3f29a12f44dcc97ab9ac258
